favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    归档: /archives
    关于我: /about

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/sonic0828']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['iamsonic', '融点Sonic的博客', 'http://iamsonic.net']
    - ['招友情连接', '有兴趣联系Sonic', 'http://iamsonic.net']


# About
about_info:
    name: "融点Sonic"
    bio: "融点Sonic的博客"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: 
duoshuo: 
uyan: 2134360

# Analytics
google_analytics: UA-99821735-1
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
