favicon: /favicon.ico


# Nav Menus
menu:
    首页: /
    归档: /archives
    关于我: /about

# Nav Shortcut Icons
nav_icons:
    - ['/images/github.svg', 'https://github.com/sonic0828']
    - ['/images/rss.svg', '/atom.xml']

# Friend Links
friend_links:
    - ['iamsonic', 'This is a link', 'http://iamsonic.net']
    - ['Demo Links', 'You can change this in your theme config', 'http://iamsonic.net']


# About
about_info:
    name: "融点Sonic"
    bio: "Sonic-融点的博客"
    avatar: "/images/avatar.png"

# Comment
# e.g disqus: seansun
disqus: iamsonic
duoshuo: 

# Analytics
google_analytics: iamsonic
tencent_analytics: 
 
# Copyright Infomation
startyear: 2017
